### ISSUE TITLE
No module named packages.six.moves.http_client

### ISSUE THREAD

**Issue by ugoogalizer** [aussieaddons/repo#70]
Hi, 

I'm trying to install and run Aussie Add-ons on a Raspberry Pi3, using LibreElec as the bareOS + Kodi.

After installation of the Aussie Add-ons zip, attempting to run any of the add-ons comes up with the following log error in Kodi. It appears that I could be missing the "[six](https://kodi.wiki/view/Add-on:Kodi_Six)" python package, but am not sure and neither can I figure out how to get it as it doesn't appear in the .  

`21:57:18.338 T:1257239456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named packages.six.moves.http_client
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.catchuptv.au.nine/default.py", line 6, in <module>
                                                import drmhelper
                                              File "/storage/.kodi/addons/script.module.drmhelper/lib/drmhelper.py", line 25, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                import urllib3
                                              File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 8, in <module>
                                              File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 11, in <module>
                                                from .exceptions import (
                                              File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/exceptions.py", line 2, in <module>
                                                from .packages.six.moves.http_client import (
                                            ImportError: No module named packages.six.moves.http_client
                                            -->End of Python script error report<--
21:57:18.354 T:1944707072   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptv.au.nine/
21:57:18.357 T:1944707072   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptv.au.nine/) failed
`

**Comment by glennguy** [comment]
Hey @ugoogalizer

Looks like you've got a script.module.requests package that might not have come from the official Kodi repo - do you have any of the 'super' repos installed? If so, disable them, remove requests and 9now and try installing 9now again

**Comment by ugoogalizer** [comment]
Thanks!  That actually helped a bunch, it turns out the "[Oz Weather](https://kodi.wiki/view/Add-on:Oz_Weather)" Kodi app had installed a bunch of conflicting "add-ons" of at least the following:

- script.common.plugin.cache
- script.module.certifi
- script.module.chardet
- script.module.idna
- script.module.urllib3
- script.module.requests
- script.module.beautifulsoup4

I uninstalled OZ Weather and all of the Aussie Add-Ons, then used the "Manage Dependencies" area in Kodi to remove all of these dependencies (and any other "Orphaned" dependencies).  After re-installing the Aussie Add-Ons, they work a treat, thanks!  Happy to mark as resolved.

Note: I never used Kodi to look up Weather, so don't care about losing that functionality much in comparison to the functionality the Aussie Add-Ons give.

**Comment by glennguy** [comment]
Great to hear!

I don't think the Oz Weather add-on is at fault. There's a 3rd party repo or repos out there that provide their own version of requests and possibly some of the other dependency add-ons which have a higher add-on version number than the ones in the official Kodi repo, so they 'supersede' the versions that actually work.

Do you have a 'fully loaded' Kodi box or did you have many other repos installed, like Ares, superrepo, tvaddons, exodus etc.?
